### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [github/brubeck#13]
I would like to point out that identifiers like "[`__BLOOM_FILTER_H`](https://github.com/github/brubeck/blob/eeef2b4f16fb4fe89ee9807e994050f07a5c32c8/src/bloom.h#L1)" and "[`__BRUBECK__H_`](https://github.com/github/brubeck/blob/eeef2b4f16fb4fe89ee9807e994050f07a5c32c8/src/brubeck.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vmg** [comment]
Thanks, I think I'll pass on this one -- not too concerned about collisions here.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
