### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [github/brubeck#14]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [multibloom_new](https://github.com/github/brubeck/blob/eeef2b4f16fb4fe89ee9807e994050f07a5c32c8/src/bloom.c#L41)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [brubeck_backend_run_threaded](https://github.com/github/brubeck/blob/eeef2b4f16fb4fe89ee9807e994050f07a5c32c8/src/backend.c#L46)

**Comment by vmg** [comment]
Thanks! Fixed upstream!

**Comment by elfring** [comment]
Where do corresponding software updates appear?

**Comment by elfring** [comment]
I find that there are still [a few update candidates](https://github.com/github/brubeck/blob/eeef2b4f16fb4fe89ee9807e994050f07a5c32c8/src/slab.c#L39 "Unchecked return values") left over [since your commit a moment ago](https://github.com/github/brubeck/commit/d893c02c33d01dda0cbaf8ad812b4dce7cfecdf0 "More error handling for pthread_create()").
How do you think about to improve the source code a bit more?
