### ISSUE TITLE
wrong error checks for recvfrom and recvmmsg

### ISSUE THREAD

**Issue by goir** [github/brubeck#18]
While testing i found when you send metrics exactly 11 or 4 characters long, those are dropped because if this checks (line 88+ in statsd.c):

    int res = recvfrom(sock, buffer,
			sizeof(buffer) - 1, 0,
			(struct sockaddr *)&reporter, &reporter_len);
    if (res == EAGAIN || res == EINTR || res == 0)
        continue;

res is either the message length or -1 on error. EAGAIN = 11 and EINTR = 4 so messages with length 4 or 11 are dropped.  This check should be res == -1 or replaced with the check further down, which check if res < 0 (line 99 in stats.c) and mark the message dropped.

I guess messages with length 4 or 11 are unlikely but maybe someone uses them.

**Comment by vmg** [comment]
Ugh, nice catch. What a silly mistake, kinda sucks that static analysis didn't catch it. I've fixed this in #20.
