### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by mhart** [github/brubeck#3]
Some of the included files appear to be GPL, cf: https://github.com/github/brubeck/blob/master/src/http/mongoose.c

This is problematic considering that brubeck doesn't appear to be GPL licensed?

Could the GPL licensed code be removed (or, less preferably, the entire project licensed GPL) so it can be used without issue?

**Comment by vmg** [comment]
Thanks for keeping us honest, @mhart. Fortunately, the part that uses Moongoose is optional and isolated, so we've made disabled it by default and removed all of Moongoose's GPL code in the repository.

I'll spend some time this week bringing over another HTTP library to the daemon (this one MIT licensed ;)) so people can still use the HTTP status endpoint.

**Comment by mhart** [comment]
Schweeet – clean abstractions ftw! :+1:
