### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Dinoshauer** [github/brubeck#5]
Hi there, I made a docker container with brubeck, are you in any way interested in this or should I just keep it for myself?

It's located here https://github.com/Dinoshauer/brubeck-docker and here https://registry.hub.docker.com/u/dinoshauer/brubeck-docker/

Also, if I've done something horribly wrong, let me know :)

**Comment by vmg** [comment]
Hi @Dinoshauer! I'm afraid I cannot judge Dockerfiles properly. I have little context and we don't use Docker on production. Afaict, I think having a repository for the Dockerfile is an OK practice, so I see nothing wrong with that. Thank you for taking the time to build it!

By the way, it seems like your Dockerfile is slightly out of date now: Brubeck now optionally depends on `libmicrohttpd-dev` if you want the stats HTTP endpoint to work. :)

**Comment by Dinoshauer** [comment]
Cool beans. Added the new dependency btw :)
