### ISSUE TITLE
Features documentation

### ISSUE THREAD

**Issue by arnaudmm** [github/brubeck#7]
Hello,

"Brubeck is missing many of the features of the original StatsD. We've only implemented what we felt was necessary for our metrics stack."

Is there a resource listing what is available or.. I have to do tests/dig into code to know that

btw thanks for sharing brubeck!

**Comment by vmg** [comment]
Hi @arnaudmm! Thanks to you for checking out brubeck! I'm afraid that StatsD has so many features that it'd be pointless to list the ones we're missing. If you have an existing statsd deployment in production though, it should be pretty straightforward to check out what Brubeck is missing just by reading the docs.

Let me know if you have any specific questions and I'll try to answer them for you. Cheers!

**Comment by joeshaw** [comment]
A little more detail would be nice.  For instance, what kinds of metrics does Brubeck support?  Does it have gauges or histograms?

**Comment by vmg** [comment]
Brubeck supports all the native metric types of StatsD: counters, timers, gauges, histograms and meters. :)

**Comment by joeshaw** [comment]
There's quite a bit of difference between the types in Brubeck and what's on https://github.com/etsy/statsd/blob/master/docs/metric_types.md.  Sets aren't supported in Brubeck, for instance, while histograms aren't mentioned in the docs.

Over the years there have been many different statsd implementations with a bunch of extensions.  It's hard to tell what any particular server supports.

Anyway, I'm happy to write up a PR for this now that I've found in the code (nicely documented, thanks) what's supported.

**Comment by vmg** [comment]
@joeshaw: Oh wow, that metrics list from StatsD *has* changed quite a bit lately. If you're willing to open a PR, that'd be really appreciated!
