### ISSUE TITLE
Repository description in unhelpful

### ISSUE THREAD

**Issue by vi** [github/brubeck#9]
It should sum up the README

**Comment by vmg** [comment]
I guess I'll have to change it then! :grin:

![](http://cdn.head-fi.org/b/b3/900x900px-LL-b31690bd_Nofunallowedrobot.jpeg)

**Comment by vi** [comment]
Repository description is the only thing (apart from used languages and name) immediately visible in search. The name of the project is not self-explanatory, so without a good description it's not possible to know what the project is about without visiting it.

Fun can be alongside with useful content, but not instead of it.
